default_install_hook_types: [pre-commit, commit-msg]

repos:
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.22.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ['@arrai-innovations/commitlint-config']

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer

    - repo: https://github.com/frnmst/md-toc
      rev: 9.0.0
      hooks:
          - id: md-toc
            stages: [pre-commit]
            args: [-p, github, -u, -l6]
            files: '.*\.md'

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # sync with ruff in pyproject.toml
      rev: v0.13.2
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format
